from pathlib import Path
from typing import Any

from forge.domain import ProjectSpec
from forge.generation.progress import ProgressReporter
from forge.infrastructure import GenerationTransaction as _  # noqa: F401


class ProjectDocumentationWriter:
    name = "project-documentation-writer"

    def run(
        self,
        spec: ProjectSpec,
        output_dir: Path,
        txn: Any,
        progress: ProgressReporter,
    ) -> None:
        agents_md = f"""# {spec.project_name} — AGENTS.md

## Domain Instructions

This project follows best practices for {spec.project_name}.

## Prompt Templates

- Task: Describe what to build
- Context: Provide relevant background
- Constraints: List technical or design constraints
"""
        txn.stage_file("AGENTS.md", agents_md)

        claude_md = f"""# {spec.project_name} — Project Context

This is a project generated by Forge.
"""
        txn.stage_file(".claude/CLAUDE.md", claude_md)
